### PR TITLE
PHP7.4 Support

### PR DESCRIPTION
**Pull request by fabis94**
It doesn't look like there's any PHP8 specific in this codebase, so why not also enable support for PHP7.4? Otherwise the userbase for this is quite limited.

I haven't tested this out yet, I wanted to discuss this first, but there's no Issues or Discussions tab for this project and thus no way to communicate with the maintainers. So I created this PR for the discussion.

### CODE REVIEW

**Comment by fabis94** [comment]
I see the following in the docs: `This plugin requires PHP 8 or later due to the use of named parameters.`, but I can't find any named parameter usage and even if there would be, to me it doesn't seem like named parameters are useful enough to mark PHP7.4 as unsupported

**Comment by owenvoke** [comment]
It requires named parameters to actually use it, not within the plugins codebase. Unless we added support for providing an [array to the `expect()` call](https://github.com/pestphp/pest-plugin-mock/blob/c2dbca6cb85a870f2e666d01aca0a3fdca7d063c/src/Mock.php), but I think that's unlikely.

We are also using Union Types in the constructor which requires PHP 8. Overall, up to @nunomaduro whether he wants to support PHP 7, but I personally think this is fine as is.

Just a note, discussions are done all on the main Pest repository to keep management simpler. 👍🏻

**Comment by fabis94** [comment]
Well it's not up to me, but I think it'd be great if the maintainers of this package could re-think this policy - PHP8 is still very new and not many projects run on it.

**Comment by nunomaduro** [comment]
No plans.

**Pull request closed without merging**
